### ISSUE TITLE
Navigation to previous page needed!

### ISSUE THREAD

**Issue by rjtnndn** [sivragav/mediumdesk#36]
Hey!
I have been using MediumDesk for a week now, and I must I say I love it! It is absolutely wonderful to be able to access Medium directly from the dock. The UI is seamless and it an absolute delight to read articles.

But my only problem with the entire app is the need to go to home every time I need to navigate back to the previous page. It really hampers the experience and flow of energy. I understand this is a community driven project, but I hope you are able to solve this asap. 

Thank you for making this app! I use it everyday, and am loving every minute it. Haven't been on the website since downloading this.

Cheers!

**Comment by chiptus** [comment]
I think this is related to issue #34. How is the medium web app works?

**Comment by sivaragavan** [comment]
@thedeany fixed this issue. Please check it out.
