### ISSUE TITLE
Sign in with Email is not working

### ISSUE THREAD

**Issue by hamxabaig** [sivragav/mediumdesk#37]
Sign in with email doesn't work because we've to open the URL in browser and it signs in medium on the browser instead of the app. I think this will be fixed if we make links of medium open in app ?
They are of the following form:
`https://medium.com/m/callback/email?token=abcdefghi&source=email-abcdefghi-auth.login--`

**Comment by TableBookspro** [comment]
Bummer. This was reported last year.

Just encountered this issue now. Guessing no resolution found.

**Comment by TableBookspro** [comment]
Just by way of casual grocking. I tried

```
open -a /Applications/MediumDesk.app https://medium.com/m/callback/email?token=XXXXXXX COPYPASTA OF THE LINK MEDIUM SENDS XXXXXX
```

Doesn't work.

**Comment by hamxabaig** [comment]
@Er-c if you wanna use the app, you can build from my repo with branch `feat/login-with-email`. I added a menu item in `File > Login` which opens the dialog box to enter the Link and then logins the user.
