### ISSUE TITLE
Create or edit article don't work

### ISSUE THREAD

**Issue by imteekay** [sivragav/mediumdesk#44]
**System**
- Running on High Sierra MacOS (10.13.6).
- Downloaded the MediumDesk current version (0.2.1)

**Actions**
- I can read my draft, but it is locked. I can't edit the article.
- I don't have a `New story` on menu (like the browser version), so I can't create a new article.
- `Cmd N` redirect to the home page
- Scroll on some pages doesn't work (example: my draft article)

My menu
<img width="232" alt="screen shot 2018-09-09 at 11 56 10" src="https://user-images.githubusercontent.com/5835798/45265936-77b7e780-b429-11e8-8146-15b55f423c0d.png">

Am I missing anything?

**Comment by thedeany** [comment]
It looks like Medium has [dropped browser support](https://help.medium.com/hc/en-us/articles/225011147-Supported-browsers) in varying "tiers" for some features. The current version of Chrome in Electron 2.0.0 is 61 which is far past the "supported" version. However, I'm assuming Medium is doing some other user-agent checking or something which is preventing the Electron app from rendering the website with all features.
